name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        run: ./android/gradlew assembleDebug

      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

